### PR TITLE
Fix ground items not showing when changing levels

### LINKED ISSUE #738: Items do not spawn on other floors when logged in first time after starting server
**Describe the bug**
Items in different floors does not spawn normally after logged in first time

**To Reproduce**
1. Start server and login to account on first floor 
2. Go to the second or third floor on lumbridge castle
3. See that no logs spawn
4. log out and log back in
5. logs have spawned.

**Expected behavior**
I should see the logs spawned or dagger. Same goes to the bronze pickaxe spawn 

**Screenshots**

https://github.com/user-attachments/assets/96a57fde-7165-44cd-9d04-b25be35dc502

**Desktop (please complete the following information):**
Newest build

### PR DESCRIPTION
**Pull request by Ilwyd**
Fixes #738

Items are now shown to the player when they change floors.

### CODE REVIEW

File: engine/src/main/kotlin/world/gregs/voidps/engine/client/update/batch/ZoneBatchUpdates.kt [hunk 1]
```diff
@@ -49,10 +49,12 @@ class ZoneBatchUpdates : Runnable {
 
     fun run(player: Player) {
         val previousZone: Zone? = player["previous_zone"]
+        val previousLevel: Int? = player["previous_level"]
         val previous = previousZone?.toRectangle(radius = player.viewport!!.localRadius)?.toZones(player.tile.level)?.toSet()
```
Comment (GregHib) [inline engine/src/main/kotlin/world/gregs/voidps/engine/client/update/batch/ZoneBatchUpdates.kt]: Why this works didn't make sense to me because `Zone` already includes a `level` so I had a look.
Turns out because `toZones(player.tile.level)` is using the current level, rather than the previous it means `previous` always contains the current zone unless teleporting.

So you can revert your changes and just change this to fix

```suggestion
        val previous = previousZone?.toRectangle(radius = player.viewport!!.localRadius)?.toZones(previousZone.level)?.toSet()
```

**Review by GregHib — CHANGES_REQUESTED** [review]

File: engine/src/main/kotlin/world/gregs/voidps/engine/client/update/batch/ZoneBatchUpdates.kt (hunk 1 above)
Comment (Ilwyd) [reply engine/src/main/kotlin/world/gregs/voidps/engine/client/update/batch/ZoneBatchUpdates.kt]: Ahh, good catch. I'll make that change :)

**Review by GregHib — APPROVED** [review]
